### ISSUE TITLE
Restructure apps

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1073]
This ticket is for discussing ideas for ways we can improve the strucuture of wagtail. Ideas are in two categories. Accepted: things we've agreed to change. Proposed: things someone thinks we should change and is being discussed in this ticket.

Accepted:
- [x] Decouple embeds, documents and images from core (https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/rich_text.py#L8-L14)
- [ ] Move forms, embeds and redirects into contrib (#1080)
- [ ] Drop "wagtail" prefix from all modules (#1077)
- [x] Separate editors picks from search and move to contrib (and rename to searchpicks?) (#1235)
- [x] Convert ``wagtailimages.Filter`` into a standard class (#2537)

Proposed:
 - Rename docs to documents (after dropping "wagtail" prefix)
 - Rename medusa to staticsitegen (#1077)
 - ~~Move sites and users into wagtailadmin~~
 - ~~Move hooks into utils~~
 - ~~Move ``RoutablePageMixin`` to ``wagtailcore/routablepage.py``~~

**Comment by kaedroho** [comment]
> Convert ``wagtailimages.Filter`` into a standard class

Implemented in #2537

**Comment by kaedroho** [comment]
Moved to an RFC: https://github.com/torchbox/wagtail-rfcs/pull/12
