### ISSUE TITLE
Styleguides for JS + CSS

### ISSUE THREAD

**Issue by JoshBarr** [torchbox/wagtail#1157]
It would be awesome to conform the JS + CSS code to a styleguide.

## JS
[AirBnB](https://github.com/airbnb/javascript) is good! What do Torchbox use? 

## CSS 
There's about half a million opinions on Google about how to structure/organise CSS + SASS, it seems! Some popular ones from the [mother-of-all front-end bookmarks](https://github.com/dypsilon/frontend-dev-bookmarks) list:

[CSSWizardry's guidelines](http://cssguidelin.es/)
[primer](http://primercss.io/guidelines/#css)
[Sass guidelines](http://sass-guidelin.es/)
[Idiomatic](https://github.com/necolas/idiomatic-css)

Also there's the architectural stuff like BEM and SMACSS, leading-dash classes as modifiers, etc. 

What should we be using?

**Comment by davecranwell** [comment]
There's no documented style for either, as you will gather. With only one developer actually doing any FE dev there's been no call for one, till now.

AirBnB's JS style is roughly what I code to most of the time anyway, so looks like a good fit to me. It's a good mixture of pragmatism and pedantry. 

For CSS guidelines I'm open to suggestions. In the past i've found none suit my personal style perfectly, but in an OS project we undoubtedly need to agree on something. 

I've blogged about my own approach before but it's not official Torchbox doctrine: http://davecranwell.com/2012/08/31/10-tips-for-better-css.html

Personally I intensely dislike BEM because the classnames look horrid and the difference between a dash and an underscore is something I repeatedly find myself looking up. That said I generally aim for a strongly object oriented class naming convention and I'm a big fan of the principals behind http://patternlab.io/. See the contents of the sass/components folder for examples. SMACSS seems like a good balance so I'd be inclined towards that.

For both JS and CSS guides I'd prefer something lightweight and not too dogmatic. Something that prevents catastrophe and incomprehension, but doesn't mean we need to painstakingly review every PR, since the time/people to do a review isn't always available.

**Comment by JoshBarr** [comment]
Cool! The JS is a quick win, since we can run [JSCS](http://jscs.info/) and have it safely conform all the code to the styleguide for us. I can do that on the master and generate a PR for it. Airbnb is 80 chars wide by default, but in keeping with your python guidelines will relax that out – 100 chars should be heaps for front-end code?  

For CSS, [Github's guidelines](http://primercss.io/guidelines/#css) plus a sprinkling of idiomatic.css will probably suffice, with the only change being we want to use 4 spaces instead of two.

There's also some good thoughts here, but I disagree with the camelCaseClassNames [https://github.com/stubbornella/oocss-code-standards](https://github.com/stubbornella/oocss-code-standards). 

## Tasks
- [ ] Conform existing JS code to AirBnb.
- [ ] Allow node packages in development so that JS code can be auto-conformed to the guide? 
- [ ] Create a one-pager README for CSS with the good bits of everyone else's guidelines.

**Comment by davecranwell** [comment]
Yeah i've read Stubbornella's guide before and like you completely disagree with camelCase, but agree almost entirely with everything else.

We're going to discuss JS/CSS at our next meeting so will let you know the outcome.

**Comment by davecranwell** [comment]
I believe this can be closed!
