### ISSUE TITLE
Compatibility with Django 1.10

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail#2723]
- [x] Update Tox and Travis config (allow failures of all builds) - #2724
- [x] `cls._deferred` check in `PageBase` - #2731

    Refs:
    * https://code.djangoproject.com/ticket/26207
    * https://docs.djangoproject.com/en/1.9/ref/models/instances/#customizing-model-loading
    * https://docs.djangoproject.com/en/1.10/ref/models/instances/#customizing-model-loading
- [x] Remove `SubfieldBase` - #2736
- [x] Fix commands that accept only positional arguments (`replace_text`, `move_pages`) - #2726
- [x] Update requirements for Django 1.10 - #2738
- [x] Decorated urlpatterns - #2741 
- [x] `model._meta.get_all_related_objects()` (see [comment](https://github.com/torchbox/wagtail/issues/2723#issuecomment-227241446); **requires tests!**) - 
- [x] `RegexURLResolver` fix for `wagtailroutablepage` - ~~#2742~~ [fixed in Django](https://github.com/django/django/pull/6809)
- [x] `TypeError: 'ModelChoiceIterator' object does not support indexing` ([regression in Django](https://github.com/django/django/pull/6794))
- [x] `FieldFile` issue ([regression in Django](https://code.djangoproject.com/ticket/26772))

List will be updated.

**Comment by m1kola** [comment]
@pjstevns `AlterModelManagers` migration - it is [a bug in Django](https://code.djangoproject.com/ticket/26643): so just ignore it.

**Comment by m1kola** [comment]
Updated. I've added check for django version (using `VERSION` form `django` module). Now it will be easier to find compatibility fixes when we decide to drop support of Django < 1.10.

**Comment by m1kola** [comment]
Probable reason of `TypeError: 'ModelChoiceIterator' object does not support indexing`:

> The unused choices keyword argument of the Select and SelectMultiple widgets’ render() method is removed. The choices argument of the render_options() method is also removed, making selected_choices the first argument.

**Comment by m1kola** [comment]
File storage issue in Django (thanks  @pjstevns): https://github.com/django/django/pull/6792

**Comment by m1kola** [comment]
I'm almost 100% sure that a reason of `TypeError: 'ModelChoiceIterator' object does not support indexing`  is [in this line](https://github.com/django/django/commit/86573861a95e5a47dc7ff906443117d75b73dca1#diff-aee6730bae795d31efec3c5d014804a9L765) (+ [comment](https://github.com/django/django/commit/86573861a95e5a47dc7ff906443117d75b73dca1#commitcomment-17912574)).

**Comment by m1kola** [comment]
`TypeError: 'ModelChoiceIterator' object does not support indexing` issues was fixed in Django: https://github.com/django/django/pull/6794

**Comment by timgraham** [comment]
There's one more item not mentioned in the checklist. I looked into replacing the removed `model._meta.get_all_related_objects()` API. According to the [migration guide](https://docs.djangoproject.com/en/1.9/ref/models/meta/#migrating-from-the-old-api), it should be something like `(f for f in self.model._meta.get_fields() if f.one_to_one and f.auto_created)`, however, [the affect lines](https://github.com/torchbox/wagtail/blob/980cc07ef0ad6cebde305eb2f7291e65a431143e/wagtail/contrib/modeladmin/views.py#L788-L7920) lack test coverage (commenting out the lines that collect `linked_objects` doesn't result in any failures) so I think that should be addressed first.

**Comment by gasman** [comment]
Just noticed that the `RegexBlock` added in #2737 has snuck in a new bit of Dj1.10-incompatible code that needs fixing. From the tests:

    /home/vagrant/wagtail/wagtail/wagtailcore/blocks/field_block.py:173: RemovedInDjango110Warning: The 'error_message' argument is deprecated. Use Field.error_messages['invalid'] instead.

**Comment by gasman** [comment]
`RegexBlock` issue fixed in 5758b54f2eac32640d408de1228bc04a8c0d5bde - I think that's everything ticked off now! If CI succeeds, I'll merge #2738 and update Travis to no longer allow failures on 1.10.

**Comment by gasman** [comment]
Completed in 03d8e738dec960e1b5ad0d11932969360a0c9bd1 + parents. Thanks all!
